# Site settings
title: Tech Dict
email: dalkluna@163.com
description: > # this means to ignore newlines until "baseurl:"  
  Build Github Pages by jeklly. 
  To record the new tech conception.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalkluna.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  dalkluna

# Build settings
markdown: kramdown